### ISSUE TITLE
Bottom navigation bar is not clickable (overlapped)

### ISSUE THREAD

**Issue by maverick-2013** [KhubaibKhan4/Crypto-KMP#1]
![Screenshot_20240614_154250](https://github.com/KhubaibKhan4/Crypto-KMP/assets/5883453/c914b4ba-7554-41cc-b933-7eff951e044c)

**Comment by maverick-2013** [comment]
PR: https://github.com/KhubaibKhan4/Crypto-KMP/pull/2

Now it looks like this:

![Screenshot_20240614_154605](https://github.com/KhubaibKhan4/Crypto-KMP/assets/5883453/24fb0951-3bbc-42ba-9949-9675fee26c0c)

**Comment by KhubaibKhan4** [comment]
Thank you for your PR And If you want to support us: https://buymeacoffee.com/khubaibkhan

**Comment by KhubaibKhan4** [comment]
Its look aww full with navigationbar padding.  
![Screenshot 2024-06-16 091703](https://github.com/KhubaibKhan4/Crypto-KMP/assets/98816544/48c13f24-1f22-4661-8b0c-5ad4402b37ab)

**Comment by maverick-2013** [comment]
I'll investigate more on this

**Comment by KhubaibKhan4** [comment]
Sure, You can do that.

**Comment by KhubaibKhan4** [comment]
You can join slack as well, there we can discuss about it too.

**Comment by maverick-2013** [comment]
Could you please invite me?

**Comment by maverick-2013** [comment]
![Screenshot_20240616_143525](https://github.com/KhubaibKhan4/Crypto-KMP/assets/5883453/a0f5f51a-bacf-4087-b8c6-15a8634f07c9)

It also has extra bottom content padding

Device: Pixel 7a, API 30

**Comment by KhubaibKhan4** [comment]
Can you provide your email? I need to provide that to invite you. Moreover, I don't know why it's displaying like that on Pixel 7 but it works perfectly fine on Gestures Devices.

**Comment by maverick-2013** [comment]
alex.timonov@gmail.com

**Comment by KhubaibKhan4** [comment]
Done.
